# Generated by Django 5.0.6 on 2024-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='discription',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default='p'),
            preserve_default=False,
        ),
    ]
